apiVersion: v1
kind: Service
metadata:
  name: notificationservice-service
  namespace: otus
spec:
  type: LoadBalancer
  ports:
  - port: 5102
    targetPort: 5100
  selector:
    app: notificationservice